<a href="https://colab.research.google.com/github/AndreyV80/NetStudy/blob/main/NumPyProjectWork.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Задание №1

In [19]:
import numpy as np

In [20]:
n = 10
x = np.arange(n)
x[::-1]    

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [21]:
#Задание №2
n = 10
x = np.arange(n)
dg_x = np.diag(x[::-1], k=0)
dg_x 
   

array([[9, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 8, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 7, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 6, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 4, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 3, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 2, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [22]:
#Сумма значений матрицы по диагонали
sum_dg_x = 0               
for i in range(n):
    sum_dg_x += dg_x[i][i]
print(sum_dg_x)
   

45


**Задание 3**
Решите систему уравнений:
4x + 2y + z = 4; 
x + 3y = 12; 
5y + 4z = -3.

In [23]:
#Задание №3
from numpy import linalg

In [24]:
a1 = np.array([[4, 2, 1], [1, 3, 0], [0, 5, 4]])
b1 = np.array([4, 12, -3])

In [25]:
linalg.solve(a1, b1)

array([ 0.46666667,  3.84444444, -5.55555556])

In [26]:
np.allclose( np.dot(a1, linalg.solve(a1, b1)), b1 )

True

In [37]:
#Задание №4


users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

In [38]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

In [39]:
ty = {}
id = 0
for i in users_stats:   
    aLength = np.sqrt( (i*i).sum() )
    bLength = np.sqrt( (next_user_stats*next_user_stats).sum() )
    np.dot( i, next_user_stats ) / ( aLength * bLength ) 
    id += 1
    ty[id] = np.dot( i, next_user_stats ) / ( aLength * bLength )
for k_, v in ty.items():
     if v == max(ty.values()):
         print('ID - ', k_,';', 'Value - ', v)

ID -  8 ; Value -  0.9486832980505138
